application: restaurant-tracker
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /putData
  script: main.putDataApp

- url: /getData
  script: main.getDataApp

- url: /search
  script: main.searchApp

- url: /details
  script: main.detailsApp

- url: /.*
  script: main.landingApp

libraries:
- name: webapp2
  version: "2.5.2"
